# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
name: Byung-cheol Kang
title: Bioinformatics specialist
email: sentim2@gmail.com
# email_title: Email (Email title override)
phone: (+82)10-5366-3411
# phone_title: Phone (Phone title override)
# website: Your website (eg. https://google.com)(optional)
# website_title: Web (Website title override)

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: jekyllrb
github_username:  Bruce-BC
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jekyll
linkedin_username: byungcheol-kang-67973311b
# jxing_username: jekyll
# pinterest_username: jekyll
# youtube_username: brucekang6474
orcid_username: 0000-0002-3015-0064
googlescholar_username: D847cGsAAAAJ

# Additional icon links
additional_links:
- title: Link name
  icon: Font Awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
  url: Link url (eg. https://google.com)
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
    Hi! my name is Byung-cheol(Or Byeong-cheol) Kang. I've been working in bioinformatics field for over 6 years, and 
    spent over 5 years in bioinformatics field, and have a strong interest in genomics and NGS data analysis.


    Bioinformatics with expertise in genomics, metagenomics, and NGS data analysis. 
    Eager to perform meaningful finding in n-dimensional data analysis through mathematical frameworks like optimal transport. 
    Proficient in bioinformatics tools, programming, and systems. Over five years of field and managerial collaborative projects
    with government agencies.

    Skilled: <mark>Metagenomics</mark>, <mark>Genomics</mark>, <mark>NGS</mark>, <mark>Bioinformatics</mark>, <mark>Systems administration</mark>, <mark>Program development</mark>

    Interested and Progressing: <mark>Optimal transport</mark>, <mark>Computational biology</mark>, <mark>Probability theory</mark>, <mark>Optimization</mark>, <mark>Machine learning</mark>
content:
  - title: Work Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left # Work experience contents1 - design ngs panel marker for foodbourne pathogen detection
        border: weak  # Value of `weak` will display a weak border below this item. # Any 
                      # other value (or no value) means no border will be displayed
        title: Design NGS panel for foodbourne pathogen detection
        # link: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
        # link_text: Link Text
        # additional_links:
        #   - title:  Github page for project (eg. sproogen/modern-resume-theme)
        #     icon: fab fa-github
        #     url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
        #   - title:  Github page for project (eg. sproogen/modern-resume-theme)
        #     icon: fab fa-github
        #     url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
        description: | # this will include new lines to allow paragraphs
          This was the first project I took the lead on at my company. 
          In line with our core value of leading food safety, 
          we embarked on the development of a kit for multiplex
          detection of foodborne pathogens using NGS technology. 
          The development period was set at one year, during 
          which I developed multiple sets of optimal primers 
          for each pathogen and built the necessary bioinformatics 
          pipeline for detection. As a result, we successfully 
          launched the NGS panel kit to the market, and 
          this achievement contributed to the company’s IPO.
      - layout: left # Work experience contents2 - genome assembly
        border: weak  # Value of `weak` will display a weak border below this item. # Any 
                      # other value (or no value) means no border will be displayed
        title: Genome assembly
        # link: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
        # link_text: Link Text
        # additional_links:
        #   - title:  Github page for project (eg. sproogen/modern-resume-theme)
        #     icon: fab fa-github
        #     url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
        #   - title:  Github page for project (eg. sproogen/modern-resume-theme)
        #     icon: fab fa-github
        #     url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
        description: | # this will include new lines to allow paragraphs
          My primary responsibility as a practitioner is to analyze microbial data. 
          At our company, we use NGS sequencers to analyze microorganisms 
          isolated and cultured from various samples. My role was to reconstruct 
          complete microbial genome information using NGS data produced by the 
          lab team. Initially, using only Illumina data, I frequently encountered 
          situations where the assembly algorithm resulted in many contigs due to 
          its limitations. After introducing a nanopore sequencer, we succeeded in 
          constructing more than 90% complete genomes and have continued to provide this service.
          Through this analysis work, I gained various practical insights. 
          The most satisfying cases were when assembly resulted in a circular
          genome in one attempt. However, sometimes, for various reasons, 
          circular genome construction fails. The most common cause is low 
          sequencing quality. In such cases, I discuss with the client and 
          attempt scaffolding as much as possible, but if necessary, 
          I use reference genomes for reference-assisted scaffolding before delivering the results.
      - layout: left # Work experience contents3 - comparative genomics
        border: weak  # Value of `weak` will display a weak border below this item. # Any 
                      # other value (or no value) means no border will be displayed
        title: Comparative genomics
        # link: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
        # link_text: Link Text
        # additional_links:
        #   - title:  Github page for project (eg. sproogen/modern-resume-theme)
        #     icon: fab fa-github
        #     url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
        #   - title:  Github page for project (eg. sproogen/modern-resume-theme)
        #     icon: fab fa-github
        #     url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
        description: | # this will include new lines to allow paragraphs
          To publish the constructed genome information, 
          it is necessary to identify genomic characteristics or 
          differences compared to previously registered species. 
          In this process, analyses such as constructing phylogenetic 
          trees based on Average Nucleotide Identity and comparing gene 
          pool variations with existing species are required. I have experience in this area, 
          using virulence factors and antibiotic resistance genes to perform comparative genetic analyses.
      - layout: left # Work experience contents4 - metagenomics
        border: weak  # Value of `weak` will display a weak border below this item. # Any 
                      # other value (or no value) means no border will be displayed
        title: Metagenomics
        # link: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
        # link_text: Link Text
        # additional_links:
        #   - title:  Github page for project (eg. sproogen/modern-resume-theme)
        #     icon: fab fa-github
        #     url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
        #   - title:  Github page for project (eg. sproogen/modern-resume-theme)
        #     icon: fab fa-github
        #     url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
        description: | # this will include new lines to allow paragraphs
          For metagenome analysis, we receive samples 
          from various sources for different requests. Unlike genome analysis, 
          which focuses solely on reconstructing genome information, metagenome 
          analysis requires careful interpretation of results according to the client’s purpose.
          A notable case was the “Incheon Chironomid Incident” in 2020. 
          At that time, unidentified chironomid larvae entered households 
          through tap water, and the Korea Water Resources Corporation 
          requested our company to analyze samples from both the source 
          water and households (with and without chironomid detection). 
          Comprehensive beta diversity analysis revealed differences 
          between source water and tap water, but no significant differences 
          among tap water samples. These results were announced by the corporation, 
          confirming that changes in the microbial community were not significantly 
          correlated with chironomid proliferation.
      - layout: left # Work experience contents5 - transcriptomics
        border: weak  # Value of `weak` will display a weak border below this item. # Any 
                      # other value (or no value) means no border will be displayed
        title: Transcriptomics
        # link: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
        # link_text: Link Text
        # additional_links:
        #   - title:  Github page for project (eg. sproogen/modern-resume-theme)
        #     icon: fab fa-github
        #     url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
        #   - title:  Github page for project (eg. sproogen/modern-resume-theme)
        #     icon: fab fa-github
        #     url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
        description: | # this will include new lines to allow paragraphs
          Genome analysis alone has limitations in fully understanding 
          the functional characteristics or environmental responses of microorganisms. 
          To overcome these limitations, I have experience leading RNA-Seq-based transcriptome 
          analysis projects. In these projects, I quantitatively analyzed changes in microbial 
          gene expression under specific environmental conditions (e.g., stress, antibiotic exposure). 
          I collaborated with the lab team throughout the process, from sample preparation and RNA 
          extraction to library construction, sequencing, data cleaning, and differential gene 
          expression (DEG) analysis. The analysis identified gene groups with significantly increased 
          expression under certain stress conditions, helping to elucidate microbial adaptation mechanisms. 
          Additionally, I provided clients with practical insights through functional annotation and 
          pathway analysis of differentially expressed genes.
      - layout: left # Work experience contents6 - develop in silico primer design as an in-house program
        border: weak  # Value of `weak` will display a weak border below this item. # Any 
                      # other value (or no value) means no border will be displayed
        title: Develop <italic>in silico</italic> primer design as an in-house program
        # link: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
        # link_text: Link Text
        # additional_links:
        #   - title:  Github page for project (eg. sproogen/modern-resume-theme)
        #     icon: fab fa-github
        #     url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
        #   - title:  Github page for project (eg. sproogen/modern-resume-theme)
        #     icon: fab fa-github
        #     url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
          
        description: | # this will include new lines to allow paragraphs
          During the development of the NGS panel kit, 
          designing primers targeting specific genetic regions of 
          various foodborne pathogens was a key challenge. As commercial 
          software could not efficiently design primers meeting our requirements, 
          I developed in-house primer discovery software. This software automatically 
          analyzes large-scale genome data to rapidly generate candidate primers that 
          are specific to target genes and minimize cross-reactivity. I utilized Python 
          and bioinformatics libraries in the development process, and the software was 
          applied to the actual panel kit development, where it demonstrated a high success 
          rate through experimental validation. Since adopting this system, the time and cost 
          required for primer design have been significantly reduced, contributing 
          to improved efficiency in our R&D operations.
  - title: Experience
    layout: list
    content:
      - layout: right
        title: Sanigen inc.
        sub_title: Bioinformatics specialist
        caption: 2020 - present
        link: Sanigen(https://sanigen.kr)
        description: | # this will include new lines to allow paragraphs
          - Whole genome sequencing(WGS) and microbial genome assembly(de novo, reference-assisted assembly), conduct microbiome analysis services.
          - Oversee analysis services, including developing NGS panel markers using comparative genomics and pan-genomics.
          - To investigate microbial genomic characteristics, utilize various open-source tools, public databases, and in-house programs.
          - Pipeline Maintenance(Git & Snakemake)
          - In-house program development; NGS panel marker development, microbial genome assembly, and microbial genomics analysis.
          - System Administrator; Server & Database management
  - title: Education
    layout: list
    content:
      - layout: top-right # MS
        title: Kyungpook National University of Hospital, School of Medicine
        sub_title: "M.S. (Major: Medical Science)"
        caption: 2016 - 2018
        description: | # this will include new lines to allow paragraphs
          Description of qualification
      - layout: top-right # BS
        title: Kyungpook National University
        sub_title: "BA (Major: Biotechnology, Minor: Psychology)"
        caption: 2008 - 2016
        description: | # this will include new lines to allow paragraphs
          Description of qualification
  - title: Publications
    layout: text
    content: |
      - Park, D. G., Kwon, J. G., Ha, E. S., **Kang, B.**, Choi, I., Kwak, J. E., ... & Lee, J. H. (2023). Novel next generation sequencing panel method for the multiple detection and identification of foodborne pathogens in agricultural wastewater. Frontiers in Microbiology, 14.
      - Park, D. G., Ha, E. S., **Kang, B.**, Choi, I., Kwak, J. E., Choi, J., ... & Lee, J. H. (2023). Development and evaluation of a next-generation Sequencing panel for the multiple detection and identification of pathogens in fermented foods. Journal of Microbiology and Biotechnology, 33(1), 83.
      - Choi, Y. A., Lee, S., Choi, J. K., **Kang, B. C.**, Kim, M. J., Dhakal, H., ... & Kim, S. H. (2020). The suppressive effect of dabrafenib, a therapeutic agent for metastatic melanoma, in IgE-mediated allergic inflammation. International Immunopharmacology, 83, 106398
      - **Kang, B. C.**, Kim, M. J., Lee, S., Choi, Y. A., Park, P. H., Shin, T. Y., ... & Kim, S. H. (2019). Nothofagin suppresses mast cell-mediated allergic inflammation. Chemico-biological interactions, 298, 1-7.
      - Lee, J. K., Lee, S., Choi, Y., Jin, M., Kim, Y. Y., **Kang, B. C.**, ... & Kim, S. H. (2018). Perfluorooctane sulfonate exacerbates mast cell-mediated allergic inflammation by the release of histamine. Molecular & Cellular Toxicology, 14(2), 173-181.
      - Kim, Y. Y., Je, I. G., Kim, M. J., **Kang, B. C.**, Choi, Y., Baek, M. C., ... & Kim, S. H. (2017). 2-Hydroxy-3-methoxybenzoic acid attenuates mast cell-mediated allergic reaction in mice via modulation of the FcεRI signaling pathway. Acta Pharmacologica Sinica, 38(1), 90-99.
      - Kim, Y. Y., Lee, S., Kim, M. J., **Kang, B. C.**, Dhakal, H., Choi, Y. A., ... & Kim, S. H. (2017). Tyrosol attenuates lipopolysaccharide-induced acute lung injury by inhibiting the inflammatory response and maintaining the alveolar capillary barrier. Food and Chemical Toxicology, 109, 526-533.
      - [Patent] Primer set of food poisoning bacteria using next generation sequencing and detection method using thereof (2022)
      - [Patent] PRIMER SET FOR DETECTING FOOD POISONING BACTERIA USING A NEXT GENERATION SEQUENCING METHOD AND METHOD FOR DETECTING FOOD POISONING BACTERIA USING THE PRIMER SET

  - title: References
    layout: text
    content: | # this will include new lines to allow paragraphs
      -	Prof. Gunhee Cho | Professor | wvx17@txstate.edu 
        Mathematics Department, Texas State University, Texas 
      -	Prof. Namkyung Kim | Assistant Professor | nortonnk@dst.ac.kr
        Department of Biomedical Laboratory Science, Daejeon Institute of Science and Technology, South Korea
      -	Prof. JinKyung Choi | Professor | jkchoi@jbnu.ac.kr 
        Department of Immunology, Jeonbuk National University Medical School, South Korea
      -	Dr. Jinjoo Kang | Lecturer | jinjoo1kang@gmail.com 
        Department of Clinical Laboratory Science, Wonkwang Health Science University, South Korea
# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
